# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftNavigationFormTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftNavigationFormTest  
   use_frameworks! # Add this if you are targeting iOS 8+ or using Swift
  
  
  pod 'Highlightr', :git => 'https://github.com/raspu/Highlightr.git'

   pod 'SwiftyJSON', :git  =>  'https://github.com/SwiftyJSON/SwiftyJSON.git'

 # pod 'SwiftyJSON', '~> 4.0' 

 
    
  target 'SwiftNavigationFormTestTests' do
	inherit! :search_paths
	# Pods for testing
  end

#  target 'SwiftNavigationFormTestUITests' do
#	inherit! :search_paths
#	# Pods for testing
#  end

end
